secret:
    databaseUrl: ENC[AES256_GCM,data:OnnwYKb6KRWrji/57IifBRyvx8J/C17xsfTqSZPZvy5kWCn9QuNP6yQPxN+26QiFRA8n74CmYdOQCc12fyUUrhYq45UTLIOlPD4xroazWRUP1aqwonKR+ikK+Prk1CX3xQ==,iv:PtR+HO/MJ0q9+XneYyANX/uoGEDmqptEp97/N10PHas=,tag:H6lvOnlx9tVLl8uNmUdY9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUm5PcUt1dnBVMTJBRktj
            ODFLUDk0MXRlWTRYdHhkVlQ5OEJ1SjJMTW5rClA2eEZndVNsMWtYUDJhRFU4b053
            U21tZHpQZHJtZHYzcG1ZSXhDUi9mMXMKLS0tIFJDU1VhcGpCVTVpcVJLa3V0ZG9v
            bGwrNXFtRmY1dE51bGFDTEt3bk5TWTQKH5Xp3PW9OE8KLNEe5rf1QvH4P4MSA3HA
            C/r16byvpKx7FbXq/yULrVYjJzHdYlPkHH4tPCg5xcMp4LfIRpHqIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t30a55ejtajmntwyvyfxk0rzfaazfrxu7nldvxk00kryj2nfpanqsnlzqw
    lastmodified: "2026-08-02T14:12:27Z"
    mac: ENC[AES256_GCM,data:1oxRp+OfPRtVmu+X7Tvm5g/zamSZr19M9Yc05jpargekEqViNLvX6GkEnSw06xVUNBezhclaaRaUMV8eZd6m37mWyec20vpbYYtC/VDMwowCHqb3Oij8Zg+FdFW28PA6Ir8jCH/3tj36dfbthJJl5C56TEow+nHvCvg35dEOrow=,iv:a4JpbrfxgMdXmP8fF7ldgZRKPJDpSnO6wBJtIiaThLY=,tag:+1c3kFkilAZDpWZOnK2vGw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
