secret:
    dbName: ENC[AES256_GCM,data:zDIxnIg=,iv:CxpbSXqwqrqJUZwJLqybQVns3/o6/mTB9i8qJL0NQkQ=,tag:F0JiYpnDthsIitQgL/ZunQ==,type:str]
    dbUser: ENC[AES256_GCM,data:+bDXEHMZlxWQOw==,iv:hGcEeI6pg4JXIOBoDQgZhUa5+XzKnIKnq5VkCN+RgrE=,tag:6QbEeJweVFuuGmKLR0bNXg==,type:str]
    dbPassword: ENC[AES256_GCM,data:Yj11kHNsA0xrWgPW71+JtQ==,iv:c/an7lKX2dp1m5IZieMOUhXjiG/TTehPrcN62yuPMJk=,tag:5rXw47G++smpz9MjafX2HA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVE1TdFZ3OHRZQWVQWURk
            Wk1IWlRoTnBKWHBZMWk0MFp6RkE1eVpzcW1ZCjRpTnVvOTJjL1NvNGRPcWFGaDZW
            NzcrckRqdFNuUVE1TjBBak4wN2s1cDQKLS0tIFR1b0YyRXJIbmxYK0tUbXdrbUlK
            RkVDMWZjMG4rdnpwdkladnZOUU1zSXcK2haZaP2qslyXEYpdJvzcMXHA1T16dYln
            VrHU9z2m0oj66sJYUUD5ACi1YPSnxvwponTmHzuwn0E+iNnH1njCvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t30a55ejtajmntwyvyfxk0rzfaazfrxu7nldvxk00kryj2nfpanqsnlzqw
    lastmodified: "2026-08-02T13:51:43Z"
    mac: ENC[AES256_GCM,data:Kitk/7dE5DrWB381JcacQcfWyzQOwDN3tttHBCzItYCHCNyVjdsBQis6Pro6duuBz/Uuu+dYSAzzN9BQORVw+tNKZF0ZlOq7FHqaBCN6ddNaAKYk3tifkm/G2pR2YJCCmQGdTaedZnJpcde5Hr5hT/Gv/Ugw7xAXh+TTl6ylzoo=,iv:EQ69sB83GNmUPscs8hivov96+gOevYbSkIWR/jprC8c=,tag:3++n1SVnEvbZ0U6zXZpesg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
